export const ActionTypes = {
  SET_TOKEN: "SET_TOKEN",
  SET_PRODUCTS: "SET_PRODUCTS",
  ADD_PRODUCT:"ADD_PRODUCT",
  DELETE_PRODUCT:"DELETE_PRODUCT",
  UPDATE_PRODUCT:"UPDATE_PRODUCT",
  SET_LOADING:"SET_LOADING",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  // REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
