export const ActionTypes = {
  SET_TOKEN: "SET_TOKEN",
  SET_PRODUCTS: "SET_PRODUCTS",
  ADD_PRODUCT:"ADD_PRODUCT",
  DELETE_PRODUCT:"DELETE_PRODUCT",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
